### ISSUE TITLE
step 6: progresses with bad input

### ISSUE THREAD

**Issue by metalivedev** [docker/docker-tutorial#35]
Try entering `docker run learn/ping www.google.com` 

Result:  `www.google.com: command not found`

But you continue on to the next step in the tutorial. This step step should be more strict with what it accepts.

**Comment by Tmarty** [comment]
Agreed, took the tuturial and came here to report or fix this. I think I found the line in the code where the step is evaluated, but I am not sure how to fix it. Is there a documentation of "command_expected" somewhere?
https://github.com/docker/docker-tutorial/blob/6edf3d18e6a71a22fbd7bd1a0f371fee924d615a/docker_tutorial/static/js/steps.coffee#L168

**Comment by charignon** [comment]
Suggested fix https://github.com/docker/docker-tutorial/pull/50
