### ISSUE TITLE
Wrong answer accepted on first search

### ISSUE THREAD

**Issue by metalivedev** [docker/docker-tutorial#37]
https://www.docker.com/tryit/#1 there is a bug with the tutorial. The 
problem can be reproduced by typing:

`you@tutorial:~$ docker search 'tutorial'`

_Found 0 results matching your query ("'tutorial'")_

_NAME DESCRIPTION_

Despite having no output for the search command due to the single quotes 
getting included in the search. The tutorial still says succeeded in a pop 
box ("You found it!"), despite not actually finding anything.

**Comment by tosbourn** [comment]
Just noticed this myself and was about to clone the repo and add a fix. It should just be a case of being a bit more strict in the search.

**Comment by charignon** [comment]
Suggested fix https://github.com/docker/docker-tutorial/pull/49
