### ISSUE TITLE
Malformed answer accepted in step 3 (hello world)

### ISSUE THREAD

**Issue by CristianCantoro** [docker/docker-tutorial#40]
Steps to reproduce:
1. Go to the [step n. 3](https://www.docker.com/tryit/#3) of the tutorial
2. type in the following:

``` bash
you@tutorial:~$ docker run learn/tutorial 'echo "hello world"
Unable to locate 'echo
```

(note the missing closing single quote)
- while the emulator returns correctly an error the popup appears anyway saying that the command was correctly executed

**Comment by fedeoasi** [comment]
I just hit this too: 

```
you@tutorial:~$ docker run learn/tutorial 'echo hello world'
2013/07/08 23:13:30 Unable to locate 'echo
you@tutorial:~$  
Great! Hellooooo World! You have just started a container and executed a program inside of it, when the program stopped, so did the container.
```

However, the following works fine:  ```docker run learn/tutorial echo hello world```

**Comment by deltreey** [comment]
I can confirm I have the same problem

**Comment by kuboj** [comment]
+1

**Comment by J7mbo** [comment]
Same problem

**Comment by rvadim** [comment]
```sh
docker run learn/tutorial echo hello world # w/o quote it works
```
