### ISSUE TITLE
"Try It" link redirects to DTR page

### ISSUE THREAD

**Issue by skelethan** [docker/docker-tutorial#51]
Opening URL http://docker.com/tryit results in this page instead of previous interactive browser tutorial

![image](https://cloud.githubusercontent.com/assets/9012349/9044847/fe3e93f2-39e4-11e5-9952-6a34d732bca2.png)

**Comment by ruffsl** [comment]
I would like to see this make a comeback at some point. It was quite simple and unintimidating, great refrence show new users the basics and that its not so difficult to learn. For those interested, you could still see what it looked like (albeit broken) with this [web archive link](https://web.archive.org/web/20150305041954/https://www.docker.com/tryit/#).
